name: release

on:
  push:
    branches:
      - goreleaser
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'

      - name: setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_PERSONAL_ACCESS_TOKEN}}' > .release-env

      - name: goreleaser release
        run: make release
